# Generated by Django 5.2.8 on 2025-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='cancellato_il',
            field=models.DateTimeField(blank=True, help_text='Soft-delete: data di cancellazione', null=True),
        ),
        migrations.AddField(
            model_name='profiloutente',
            name='ruolo_utente',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('docente', 'Docente'), ('studente', 'Studente'), ('assistente', 'Assistente'), ('altro', 'Altro')], default='studente', help_text='Ruolo principale dell’utente nel sistema', max_length=30, verbose_name='Ruolo Utente'),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='cancellato_il',
            field=models.DateTimeField(blank=True, help_text='Soft-delete: data di cancellazione', null=True),
        ),
        migrations.AddField(
            model_name='ubicazionerisorsa',
            name='codice_meccanografico',
            field=models.CharField(blank=True, help_text='Codice scuola/plesso corrispondente (per matching con lookup_unica)', max_length=20, verbose_name='Codice Meccanografico'),
        ),
        migrations.AlterField(
            model_name='informazioniscuola',
            name='indirizzo_scuola',
            field=models.TextField(help_text='Indirizzo completo (compatibile con servizi di geocoding come OpenStreetMap/Nominatim)', verbose_name='Indirizzo Completo Scuola'),
        ),
    ]
