"""
Data migration to create Django core tables in PostgreSQL if they don't exist.
This is needed for Render deployment where migrate might not create contrib tables properly.
"""

from django.db import migrations, connection


def create_django_core_tables(apps, schema_editor):
    """
    Optimized creation of Django core tables using raw SQL.
    Batches operations to minimize database round trips.
    This fixes the missing django_session table causing login errors.
    """
    # Only run for PostgreSQL
    if connection.vendor != 'postgresql':
        return

    # ========================================
    # CREATE ALL TABLES IN ONE BATCH
    # ========================================
    schema_editor.execute("""
        -- Core Django tables - all CREATE statements batched
        CREATE TABLE IF NOT EXISTS "django_content_type" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "app_label" varchar(100) NOT NULL,
            "model" varchar(100) NOT NULL,
            UNIQUE ("app_label", "model")
        );

        CREATE TABLE IF NOT EXISTS "auth_permission" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "name" varchar(255) NOT NULL,
            "content_type_id" bigint NOT NULL,
            "codename" varchar(100) NOT NULL,
            UNIQUE ("content_type_id", "codename")
        );

        CREATE TABLE IF NOT EXISTS "auth_group" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "name" varchar(150) NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS "auth_user" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "password" varchar(128) NOT NULL,
            "last_login" timestamp WITH TIME ZONE,
            "is_superuser" boolean NOT NULL DEFAULT false,
            "username" varchar(150) NOT NULL UNIQUE,
            "first_name" varchar(150) NOT NULL,
            "last_name" varchar(150) NOT NULL,
            "email" varchar(254) NOT NULL,
            "is_staff" boolean NOT NULL DEFAULT false,
            "is_active" boolean NOT NULL DEFAULT true,
            "date_joined" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS "auth_group_permissions" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "group_id" bigint NOT NULL,
            "permission_id" bigint NOT NULL,
            UNIQUE ("group_id", "permission_id")
        );

        CREATE TABLE IF NOT EXISTS "auth_user_groups" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" bigint NOT NULL,
            "group_id" bigint NOT NULL,
            UNIQUE ("user_id", "group_id")
        );

        CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" bigint NOT NULL,
            "permission_id" bigint NOT NULL,
            UNIQUE ("user_id", "permission_id")
        );

        -- THE KEY MISSING TABLE - django_session
        CREATE TABLE IF NOT EXISTS "django_session" (
            "session_key" varchar(40) NOT NULL PRIMARY KEY,
            "session_data" text NOT NULL,
            "expire_date" timestamp WITH TIME ZONE NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "django_admin_log" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "action_time" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "object_id" text,
            "object_repr" varchar(200) NOT NULL,
            "action_flag" smallint NOT NULL,
            "change_message" text NOT NULL,
            "content_type_id" bigint,
            "user_id" bigint NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "django_site" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "domain" varchar(100) NOT NULL,
            "name" varchar(50) NOT NULL
        );
    """)

    # ========================================
    # CREATE ALL INDEXES IN ONE BATCH
    # ========================================
    schema_editor.execute("""
        -- Performance indexes for Django core tables
        CREATE INDEX IF NOT EXISTS "auth_permission_content_type_id_codename_idx" ON "auth_permission" ("content_type_id", "codename");
        CREATE INDEX IF NOT EXISTS "auth_group_permissions_group_id_idx" ON "auth_group_permissions" ("group_id");
        CREATE INDEX IF NOT EXISTS "auth_group_permissions_permission_id_idx" ON "auth_group_permissions" ("permission_id");
        CREATE INDEX IF NOT EXISTS "auth_user_groups_user_id_idx" ON "auth_user_groups" ("user_id");
        CREATE INDEX IF NOT EXISTS "auth_user_groups_group_id_idx" ON "auth_user_groups" ("group_id");
        CREATE INDEX IF NOT EXISTS "auth_user_user_permissions_user_id_idx" ON "auth_user_user_permissions" ("user_id");
        CREATE INDEX IF NOT EXISTS "auth_user_user_permissions_permission_id_idx" ON "auth_user_user_permissions" ("permission_id");
        CREATE INDEX IF NOT EXISTS "django_admin_log_content_type_id_idx" ON "django_admin_log" ("content_type_id");
        CREATE INDEX IF NOT EXISTS "django_admin_log_user_id_idx" ON "django_admin_log" ("user_id");
        CREATE INDEX IF NOT EXISTS "django_session_expire_date_idx" ON "django_session" ("expire_date");
    """)

    # ========================================
    # ADD FOREIGN KEY CONSTRAINTS IN ONE BATCH
    # ========================================
    schema_editor.execute("""
        -- Foreign key constraints between Django core tables
        ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_fkey"
            FOREIGN KEY ("content_type_id") REFERENCES "django_content_type"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

        ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_fkey"
            FOREIGN KEY ("group_id") REFERENCES "auth_group"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_permission_id_fkey"
            FOREIGN KEY ("permission_id") REFERENCES "auth_permission"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

        ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_fkey"
            FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_fkey"
            FOREIGN KEY ("group_id") REFERENCES "auth_group"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

        ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_fkey"
            FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_permission_id_fkey"
            FOREIGN KEY ("permission_id") REFERENCES "auth_permission"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

        ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_fkey"
            FOREIGN KEY ("content_type_id") REFERENCES "django_content_type"("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_fkey"
            FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
    """)

    # ========================================
    # INSERT INITIAL DATA
    # ========================================
    schema_editor.execute("""
        -- Insert default Django site
        INSERT INTO "django_site" ("id", "domain", "name")
        VALUES (1, 'example.com', 'example.com')
        ON CONFLICT ("id") DO NOTHING;
    """)


def reverse_create_django_core_tables(apps, schema_editor):
    # Reverse operation - drop tables if they exist
    # This is optional and can be left empty
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_django_core_tables,
            reverse_code=reverse_create_django_core_tables
        ),
    ]
