# Generated by Django 5.2.8 on 2025-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadispositivo',
            name='nome',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
