# Generated by Django 5.2.8 on 2025-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_dispositivo_cancellato_il_profiloutente_ruolo_utente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicazionerisorsa',
            name='codice_meccanografico',
            field=models.CharField(blank=True, help_text='Codice scuola/plesso (CODICESCUOLA dal CSV) - identificatore univoco', max_length=20, unique=True, verbose_name='Codice Meccanografico'),
        ),
        migrations.AlterField(
            model_name='ubicazionerisorsa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
