# Generated by Django 5.2.8 on 2025-11-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_alter_ubicazionerisorsa_codice_meccanografico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('stato_assegnazione', models.CharField(choices=[('assegnato', 'Assegnato'), ('in_preparazione', 'In Preparazione'), ('restituito', 'Restituito'), ('danneggiato', 'Danneggiato'), ('smarrito', 'Smarrito')], default='assegnato', max_length=20)),
                ('data_assegnazione', models.DateTimeField(auto_now_add=True)),
                ('data_restituzione', models.DateTimeField(blank=True, null=True)),
                ('note_assegnazione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Prenotazione',
                'verbose_name_plural': 'Dispositivi Prenotazioni',
            },
        ),
        migrations.RenameIndex(
            model_name='prenotazione',
            new_name='prenotazion_stato_ec6071_idx',
            old_name='prenotazion_stato_i_9c5bfb_idx',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='armadio',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='edificio',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='piano',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='dispositivi_selezionati',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='codice_fiscale_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='cognome_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='data_nascita_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='email_personale_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='nome_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='sesso_utente',
        ),
        migrations.RemoveField(
            model_name='sessioneutente',
            name='telefono_utente',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivi_creati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivi_modificati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ubicazione',
            field=models.ForeignKey(blank=True, help_text='Localizzazione fisica del dispositivo', null=True, on_delete=django.db.models.deletion.PROTECT, to='prenotazioni.ubicazionerisorsa', verbose_name='Ubicazione Dispositivo'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenotazioni_modificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='numero_persone',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risorse_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risorse_modificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('bozza', 'In Bozza'), ('in_attesa_approvazione', 'In Attesa di Approvazione'), ('approvata', 'Approvata'), ('in_corso', 'In Corso'), ('completata', 'Completata'), ('annullata', 'Annullata'), ('rinviata', 'Rinviata')], default='bozza', max_length=30),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='localizzazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenotazioni.ubicazionerisorsa', verbose_name='Ubicazione Risorsa'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['ubicazione'], name='prenotazion_ubicazi_02a80a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['cancellato_il'], name='prenotazion_cancell_402cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='prenotazione',
            index=models.Index(fields=['stato', 'inizio'], name='prenotazion_stato_4c28ec_idx'),
        ),
        migrations.AddIndex(
            model_name='prenotazione',
            index=models.Index(fields=['cancellato_il'], name='prenotazion_cancell_82bba1_idx'),
        ),
        migrations.AddIndex(
            model_name='risorsa',
            index=models.Index(fields=['cancellato_il'], name='prenotazion_cancell_389b22_idx'),
        ),
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.CheckConstraint(condition=models.Q(('fine__gt', models.F('inizio'))), name='prenotazione_fine_dopo_inizio'),
        ),
        migrations.AddField(
            model_name='prenotazionedispositivo',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni_prenotazione', to='prenotazioni.dispositivo'),
        ),
        migrations.AddField(
            model_name='prenotazionedispositivo',
            name='prenotazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi_assegnati', to='prenotazioni.prenotazione'),
        ),
        migrations.AddIndex(
            model_name='prenotazionedispositivo',
            index=models.Index(fields=['prenotazione', 'stato_assegnazione'], name='prenotazion_prenota_60c30c_idx'),
        ),
        migrations.AddIndex(
            model_name='prenotazionedispositivo',
            index=models.Index(fields=['dispositivo', 'data_assegnazione'], name='prenotazion_disposi_36e8ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazionedispositivo',
            unique_together={('prenotazione', 'dispositivo')},
        ),
    ]
