\".PHONY: help install migrate run test clean\"  
\"help:\"  
\"	@echo \\\"Available commands:\\\"\"  
\"	@echo \\\"install  - Install dependencies\\\"\"  
\"	@echo \\\"migrate - Run database migrations\\\"\" 
\"	@echo \\\"run      - Run development server\\\"\"  
\"	@echo \\\"test     - Run tests\\\"\"  
\"	@echo \\\"clean    - Clean temporary files\\\"\"  
\"\" 
\"install:\"  
\"	pip install -r requirements.txt\"  
\"\"  
\"migrate:\"  
\"	python manage.py migrate\"  
\"\" 
\"run:\"  
\"	python manage.py runserver\"  
\"\"  
\"test:\"  
\"	python manage.py test prenotazioni\"  
\"\" 
\"clean:\"  
\"	find . -name \\\"*.pyc\\\" -delete\"  
\"	find . -name \\\"__pycache__\\\" -type d -exec rm -rf {} +\"  
\"	rm -rf staticfiles\" 
