-- 🚀 SOLUZIONE IMMEDIATA - ESECUZIONE DIRETTA DATABASE NEON
-- Questo script SQL deve essere eseguito DIRETTAMENTE in Neon Console
-- Vai su https://neon.tech → Il tuo database → SQL Editor → Esegui questo script

-- ============================================
-- CREAZIONE TABELLE MANCANTI SISTEMA PRENOTAZIONI
-- ============================================

-- 1. TABELLABASE UTENTE (quella mancante che causa l'errore)
CREATE TABLE IF NOT EXISTS "prenotazioni_utente" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp WITH TIME ZONE,
    "is_superuser" boolean NOT NULL DEFAULT false,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL DEFAULT '',
    "last_name" varchar(150) NOT NULL DEFAULT '',
    "email" varchar(254) NOT NULL UNIQUE,
    "is_staff" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "date_joined" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ruolo" varchar(20) NOT NULL DEFAULT 'studente',
    "email_verificato" boolean NOT NULL DEFAULT false,
    "telefono_verificato" boolean NOT NULL DEFAULT false,
    "account_attivo" boolean NOT NULL DEFAULT true,
    "pin_tentativi" integer NOT NULL DEFAULT 0,
    "ultimo_pin_tentativo" timestamp WITH TIME ZONE,
    "pin_bloccato_fino" timestamp WITH TIME ZONE,
    "ultimo_login_ip" inet,
    "data_creazione" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. USERPROFILE
CREATE TABLE IF NOT EXISTS "prenotazioni_userprofile" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar(100) NOT NULL,
    "cognome" varchar(100) NOT NULL,
    "sesso" varchar(10) DEFAULT '',
    "data_nascita" date,
    "codice_fiscale" varchar(16) DEFAULT '',
    "telefono" varchar(20) DEFAULT '',
    "email_personale" varchar(254) DEFAULT '',
    "numero_matricola" varchar(20) DEFAULT '',
    "classe" varchar(20) DEFAULT '',
    "dipartimento" varchar(100) DEFAULT '',
    "materia_insegnamento" varchar(100) DEFAULT '',
    "preferenze_notifica" jsonb NOT NULL DEFAULT '{}',
    "preferenze_lingua" varchar(10) NOT NULL DEFAULT 'it',
    "fuso_orario" varchar(50) NOT NULL DEFAULT 'Europe/Rome',
    "attivo" boolean NOT NULL DEFAULT true,
    "verificato" boolean NOT NULL DEFAULT false,
    "data_verifica" timestamp WITH TIME ZONE,
    "ultimo_accesso" timestamp WITH TIME ZONE,
    "creato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modificato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" bigint NOT NULL UNIQUE
);

-- 3. DEVICE
CREATE TABLE IF NOT EXISTS "prenotazioni_device" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar(100) NOT NULL,
    "modello" varchar(100) DEFAULT '',
    "marca" varchar(100) NOT NULL,
    "serie" varchar(100) DEFAULT '',
    "codice_inventario" varchar(50) NOT NULL UNIQUE,
    "tipo" varchar(20) NOT NULL,
    "specifiche" jsonb NOT NULL DEFAULT '{}',
    "stato" varchar(20) NOT NULL DEFAULT 'disponibile',
    "attivo" boolean NOT NULL DEFAULT true,
    "edificio" varchar(50) DEFAULT '',
    "piano" varchar(20) DEFAULT '',
    "aula" varchar(50) DEFAULT '',
    "armadio" varchar(50) DEFAULT '',
    "data_acquisto" date,
    "data_scadenza_garanzia" date,
    "valore_acquisto" numeric(10, 2),
    "note" text DEFAULT '',
    "ultimo_controllo" timestamp WITH TIME ZONE,
    "prossima_manutenzione" timestamp WITH TIME ZONE,
    "creato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modificato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "categoria_id" bigint
);

-- 4. RESOURCE
CREATE TABLE IF NOT EXISTS "prenotazioni_resource" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar(100) NOT NULL,
    "codice" varchar(20) NOT NULL UNIQUE,
    "descrizione" text DEFAULT '',
    "tipo" varchar(20) NOT NULL,
    "categoria" varchar(50) DEFAULT '',
    "capacita_massima" integer,
    "postazioni_disponibili" integer NOT NULL DEFAULT 0,
    "orari_apertura" jsonb NOT NULL DEFAULT '{}',
    "feriali_disponibile" boolean NOT NULL DEFAULT true,
    "weekend_disponibile" boolean NOT NULL DEFAULT false,
    "festivo_disponibile" boolean NOT NULL DEFAULT false,
    "attivo" boolean NOT NULL DEFAULT true,
    "manutenzione" boolean NOT NULL DEFAULT false,
    "bloccato" boolean NOT NULL DEFAULT false,
    "prenotazione_anticipo_minimo" integer NOT NULL DEFAULT 1,
    "prenotazione_anticipo_massimo" integer NOT NULL DEFAULT 30,
    "durata_minima_minuti" integer NOT NULL DEFAULT 30,
    "durata_massima_minuti" integer NOT NULL DEFAULT 240,
    "allow_overbooking" boolean NOT NULL DEFAULT false,
    "overbooking_limite" integer NOT NULL DEFAULT 0,
    "note_amministrative" text DEFAULT '',
    "note_utenti" text DEFAULT '',
    "creato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modificato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "localizzazione_id" bigint
);

-- 5. BOOKING (PRENOTAZIONI)
CREATE TABLE IF NOT EXISTS "prenotazioni_booking" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "inizio" timestamp WITH TIME ZONE NOT NULL,
    "fine" timestamp WITH TIME ZONE NOT NULL,
    "quantita" integer NOT NULL DEFAULT 1,
    "priorita" varchar(20) NOT NULL DEFAULT 'normale',
    "scopo" varchar(200) DEFAULT '',
    "note" text DEFAULT '',
    "note_amministrative" text DEFAULT '',
    "setup_needed" boolean NOT NULL DEFAULT false,
    "cleanup_needed" boolean NOT NULL DEFAULT false,
    "approvazione_richiesta" boolean NOT NULL DEFAULT false,
    "data_approvazione" timestamp WITH TIME ZONE,
    "notifiche_inviate" jsonb NOT NULL DEFAULT '[]',
    "ultimo_aggiornamento_notifica" timestamp WITH TIME ZONE,
    "creato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modificato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cancellato_il" timestamp WITH TIME ZONE,
    "utente_id" bigint NOT NULL,
    "risorsa_id" bigint NOT NULL,
    "stato_id" bigint,
    "approvato_da_id" bigint
);

-- 6. NOTIFICATION
CREATE TABLE IF NOT EXISTS "prenotazioni_notification" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" varchar(20) NOT NULL,
    "canale" varchar(20) NOT NULL,
    "titolo" varchar(200) DEFAULT '',
    "messaggio" text NOT NULL,
    "dati_aggiuntivi" jsonb NOT NULL DEFAULT '{}',
    "stato" varchar(20) NOT NULL DEFAULT 'pending',
    "tentativo_corrente" integer NOT NULL DEFAULT 0,
    "ultimo_tentativo" timestamp WITH TIME ZONE,
    "prossimo_tentativo" timestamp WITH TIME ZONE,
    "inviata_il" timestamp WITH TIME ZONE,
    "consegnata_il" timestamp WITH TIME ZONE,
    "errore_messaggio" text DEFAULT '',
    "creato_il" timestamp WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "utente_id" bigint NOT NULL,
    "template_id" bigint,
    "related_booking_id" bigint,
    "related_user_id" bigint
);

-- ============================================
-- INDICI PER PERFORMANCE
-- ============================================

-- Indici Utente
CREATE INDEX IF NOT EXISTS "prenotazioni_utente_ruolo_idx" ON "prenotazioni_utente" ("ruolo");
CREATE INDEX IF NOT EXISTS "prenotazioni_utente_email_verificato_idx" ON "prenotazioni_utente" ("email_verificato");
CREATE INDEX IF NOT EXISTS "prenotazioni_utente_account_attivo_idx" ON "prenotazioni_utente" ("account_attivo");

-- Indici UserProfile
CREATE INDEX IF NOT EXISTS "prenotazioni_userprofile_user_idx" ON "prenotazioni_userprofile" ("user_id");
CREATE INDEX IF NOT EXISTS "prenotazioni_userprofile_attivo_idx" ON "prenotazioni_userprofile" ("attivo");
CREATE INDEX IF NOT EXISTS "prenotazioni_userprofile_verificato_idx" ON "prenotazioni_userprofile" ("verificato");

-- Indici Device
CREATE INDEX IF NOT EXISTS "prenotazioni_device_codice_inventario_idx" ON "prenotazioni_device" ("codice_inventario");
CREATE INDEX IF NOT EXISTS "prenotazioni_device_tipo_stato_idx" ON "prenotazioni_device" ("tipo", "stato");
CREATE INDEX IF NOT EXISTS "prenotazioni_device_categoria_idx" ON "prenotazioni_device" ("categoria_id");
CREATE INDEX IF NOT EXISTS "prenotazioni_device_attivo_idx" ON "prenotazioni_device" ("attivo");

-- Indici Resource
CREATE INDEX IF NOT EXISTS "prenotazioni_resource_codice_idx" ON "prenotazioni_resource" ("codice");
CREATE INDEX IF NOT EXISTS "prenotazioni_resource_tipo_attivo_idx" ON "prenotazioni_resource" ("tipo", "attivo");
CREATE INDEX IF NOT EXISTS "prenotazioni_resource_localizzazione_idx" ON "prenotazioni_resource" ("localizzazione_id");

-- Indici Booking
CREATE INDEX IF NOT EXISTS "prenotazioni_booking_utente_inizio_idx" ON "prenotazioni_booking" ("utente_id", "inizio");
CREATE INDEX IF NOT EXISTS "prenotazioni_booking_risorsa_inizio_fine_idx" ON "prenotazioni_booking" ("risorsa_id", "inizio", "fine");
CREATE INDEX IF NOT EXISTS "prenotazioni_booking_stato_idx" ON "prenotazioni_booking" ("stato_id");
CREATE INDEX IF NOT EXISTS "prenotazioni_booking_inizio_fine_idx" ON "prenotazioni_booking" ("inizio", "fine");

-- Indici Notification
CREATE INDEX IF NOT EXISTS "prenotazioni_notification_utente_stato_idx" ON "prenotazioni_notification" ("utente_id", "stato");
CREATE INDEX IF NOT EXISTS "prenotazioni_notification_tipo_stato_idx" ON "prenotazioni_notification" ("tipo", "stato");
CREATE INDEX IF NOT EXISTS "prenotazioni_notification_creato_il_idx" ON "prenotazioni_notification" ("creato_il");

-- ============================================
-- FOREIGN KEYS
-- ============================================

-- UserProfile -> Utente
ALTER TABLE "prenotazioni_userprofile" ADD CONSTRAINT "prenotazioni_userprofile_user_id_fkey" 
    FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE;

-- Device -> DeviceCategory (se esiste)
ALTER TABLE "prenotazioni_device" ADD CONSTRAINT "prenotazioni_device_categoria_id_fkey" 
    FOREIGN KEY ("categoria_id") REFERENCES "prenotazioni_devicecategory"("id") ON DELETE SET NULL;

-- Resource -> ResourceLocation (se esiste)
ALTER TABLE "prenotazioni_resource" ADD CONSTRAINT "prenotazioni_resource_localizzazione_id_fkey" 
    FOREIGN KEY ("localizzazione_id") REFERENCES "prenotazioni_resourcelocation"("id") ON DELETE SET NULL;

-- Booking -> Utente
ALTER TABLE "prenotazioni_booking" ADD CONSTRAINT "prenotazioni_booking_utente_id_fkey" 
    FOREIGN KEY ("utente_id") REFERENCES "auth_user"("id") ON DELETE CASCADE;

-- Booking -> Resource
ALTER TABLE "prenotazioni_booking" ADD CONSTRAINT "prenotazioni_booking_risorsa_id_fkey" 
    FOREIGN KEY ("risorsa_id") REFERENCES "prenotazioni_resource"("id") ON DELETE CASCADE;

-- Booking -> BookingStatus (se esiste)
ALTER TABLE "prenotazioni_booking" ADD CONSTRAINT "prenotazioni_booking_stato_id_fkey" 
    FOREIGN KEY ("stato_id") REFERENCES "prenotazioni_bookingstatus"("id") ON DELETE SET NULL;

-- Booking -> Utente (approvato_da)
ALTER TABLE "prenotazioni_booking" ADD CONSTRAINT "prenotazioni_booking_approvato_da_id_fkey" 
    FOREIGN KEY ("approvato_da_id") REFERENCES "auth_user"("id") ON DELETE SET NULL;

-- Notification -> Utente
ALTER TABLE "prenotazioni_notification" ADD CONSTRAINT "prenotazioni_notification_utente_id_fkey" 
    FOREIGN KEY ("utente_id") REFERENCES "auth_user"("id") ON DELETE CASCADE;

-- Notification -> NotificationTemplate (se esiste)
ALTER TABLE "prenotazioni_notification" ADD CONSTRAINT "prenotazioni_notification_template_id_fkey" 
    FOREIGN KEY ("template_id") REFERENCES "prenotazioni_notificationtemplate"("id") ON DELETE SET NULL;

-- Notification -> Booking
ALTER TABLE "prenotazioni_notification" ADD CONSTRAINT "prenotazioni_notification_related_booking_id_fkey" 
    FOREIGN KEY ("related_booking_id") REFERENCES "prenotazioni_booking"("id") ON DELETE SET NULL;

-- Notification -> Utente (related_user)
ALTER TABLE "prenotazioni_notification" ADD CONSTRAINT "prenotazioni_notification_related_user_id_fkey" 
    FOREIGN KEY ("related_user_id") REFERENCES "auth_user"("id") ON DELETE SET NULL;

-- ============================================
-- DATI INIZIALI ESSENZIALI
-- ============================================

-- Inserisci un admin di base per test
INSERT INTO "auth_user" (
    "id", "password", "username", "first_name", "last_name", "email", 
    "is_staff", "is_superuser", "is_active", "date_joined", "ruolo"
) VALUES (
    1, 'pbkdf2_sha256$600000$...', 'admin', 'Admin', 'Sistema', 'admin@isufol.it',
    true, true, true, CURRENT_TIMESTAMP, 'admin'
) ON CONFLICT (username) DO NOTHING;

-- Inserisci una configurazione di base
INSERT INTO "prenotazioni_configuration" ("chiave", "valore", "tipo", "descrizione") VALUES
('EMAIL_HOST', 'smtp-relay.brevo.com', 'email', 'Server SMTP'),
('BOOKING_START_HOUR', '08:00', 'booking', 'Orario inizio'),
('BOOKING_END_HOUR', '18:00', 'booking', 'Orario fine'),
('SCHOOL_NAME', 'ISIS Follonica', 'system', 'Nome scuola')
ON CONFLICT (chiave) DO NOTHING;

-- Inserisci informazioni scuola
INSERT INTO "prenotazioni_schoolinfo" (
    "id", "nome_completo", "nome_breve", "codice_meccanografico", 
    "email_istituzionale", "sito_web"
) VALUES (
    1, 'Istituto Statale di Istruzione Superiore di Follonica',
    'ISIS Follonica', 'GRIS00700X', 'info@isufol.it', 'https://www.isufol.edu.it'
) ON CONFLICT (id) DO NOTHING;

-- ============================================
-- COMPLETAMENTO
-- ============================================

-- Verifica che tutte le tabelle siano state create
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'prenotazioni_%';

-- Se vedi "prenotazioni_utente" nella lista, il problema è risolto!
-- Nota: potrebbe apparire come "auth_user" se Django usa il table prefix personalizzato
